name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"
      
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: windows-10-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Rinish94/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
